-- Create the activity_log table
create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  lesson_id bigint references public.lessons(id) on delete set null,
  action_type text not null check (action_type in ('login', 'view', 'download')),
  created_at timestamptz not null default now()
);

alter table public.activity_log enable row level security;

-- Students can insert only their own rows
create policy "Students can insert their own activity"
on public.activity_log
for insert
to authenticated
with check (
  student_id = auth.uid()
);

-- Only the admin can read activity rows
create policy "Admin can read all activity"
on public.activity_log
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and lower(p.email) = 'admin@gmail.com'
  )
);

-- No SELECT policy for students, so other students cannot read each other's activity
